###
POST http://localhost:5000/adresses/create
Content-Type: application/json

{
    "street": "petanque",
    "number": 42,
    "city": "Marseille",
    "country": "Listembour",
    "email": "illls@matrix.com",
    "idOldAdress":""
}

###
GET http://localhost:5000/adresses