###
POST  http://localhost:5000/clubs/register
Content-Type: application/json

{
    "password" : "marti",
    "name" : "jean",
    "email" : "jeab@matrix.com"
}

###
GET http://localhost:5000/clubs

###
GET http://localhost:5000/clubs/memberRequests?email_club=jeab@matrix.com&role=player

###
GET http://localhost:5000/clubs/memberRequests?email_club=jeab@matrix.com&role=coach

###
POST  http://localhost:5000/clubs/acceptNewMember
Content-Type: application/json

{
    "email_member" : "jean@matrix.com",
    "role" : "coach",
    "email_club" : "jeab@matrix.com"
}

###
POST  http://localhost:5000/clubs/acceptNewMember
Content-Type: application/json

{
    "email_member" : "jeabn@matrix.com",
    "role" : "player",
    "email_club" : "jeab@matrix.com"
}

###
GET http://localhost:5000/clubs/members?email_club=jeab@matrix.com&role=player

###
GET http://localhost:5000/clubs/members?email_club=jeab@matrix.com&role=coach

###
DELETE http://localhost:5000/clubs/removeMember
Content-Type: application/json

{
    "email_member" : "jean@matrix.com",
    "email_club" : "jeab@matrix.com"
}

###
DELETE http://localhost:5000/clubs/removeAllClubs