###
POST  http://localhost:5000/clubs/register
Content-Type: application/json

{
    "password" : "marti",
    "name" : "RSCA",
    "email" : "jeahdfushkfsfb@matrix.com"
}

###
GET http://localhost:5000/clubs

###
GET http://localhost:5000/clubs/memberRequests?email_club=k@k.com&role=player

###
GET http://localhost:5000/clubs/memberRequests?email_club=k@k.com&role=coach

###
POST  http://localhost:5000/clubs/acceptNewMember
Content-Type: application/json

{
    "email_member" : "jeromeCoach@gmail.com",
    "role" : "coach",
    "email_club" : "k@k.com"
}

###
POST  http://localhost:5000/clubs/acceptNewMember
Content-Type: application/json

{
    "email_member" : "messi@leo.com",
    "role" : "player",
    "email_club" : "k@k.com"
}

###
GET http://localhost:5000/clubs/members?email_club=k@k.com&role=player

###
GET http://localhost:5000/clubs/members?email_club=k@k.com&role=coach

###
DELETE http://localhost:5000/clubs/removeMember
Content-Type: application/json

{
    "email_member" : "lbj@hotmail.com",
    "email_club" : "k@k.com"
}

###
DELETE http://localhost:5000/clubs/removeAllClubs

###
GET http://localhost:5000/clubs/getTeamsClub?email=uaae@hotmail.com