###
POST http://localhost:5000/coachs/register
Content-Type: application/json

{
    "lastname" : "marti",
    "firstname" : "jean",
    "email" : "jean@matrix.com",
    "password" : "yayaya",
    "age" : 16
}

###
GET http://localhost:5000/coachs


###
POST http://localhost:5000/coachs/applyClub
Content-Type: application/json

{
    "email_coach": "jean@matrix.com",
    "email_club" : "jeab@matrix.com"
}

###
GET http://localhost:5000/coachs/coachClub?email_coach=jean@matrix.com

###
DELETE http://localhost:5000/coachs/leaveClub
Content-Type: application/json

{
    "email_coach": "jean@matrix.com",
    "email_club" : "jeab@matrix.com"
}