###
POST http://localhost:5000/notifications/create
Content-Type: application/json

{
    "content": "Jafar je suis coincé",
    "email": "jean@matrix.com"
}

###
GET http://localhost:5000/notifications

### 
GET http://localhost:5000/notifications/getNotifications?email_user=jean@matrix.com

###
#delete all notif CAREFULL!!!!
DELETE http://localhost:5000/notifications/removeAllNotifications

###
POST http://localhost:5000/notifications/updateState
Content-Type: application/json

{
    "id": "3ac99ce1-f14b-4fd6-8ca8-01a45f7fb728"
}