###
POST http://localhost:5000/sports/create
Content-Type: application/json

{
    "name": "rollers"
}

###
GET http://localhost:5000/sports

###
PUT http://localhost:5000/sports/addSport
Content-Type: application/json

{
    "name": "rollers",
    "role": "player",
    "email": "jeabn@matrix.com",
    "nameOldSport": "petanque"
}