###
POST http://localhost:5000/sports/create
Content-Type: application/json

{
    "name": "rollers"
}

###
GET http://localhost:5000/sports

###
PUT http://localhost:5000/sports/addSport
Content-Type: application/json
Authorize : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzkyNGM5NWItZjNjYS00OWM5LWE1NGUtOTQ5ZWQ3MmUzNWQ1IiwiZXhwIjoxNjcwODQ4NjAzfQ.0M9RHwdq2dsO_nTZK8F2jWXLFEmyF-Z-kFGM47qt3zk

{
    "name": "rollers",
    "email": "illls@matrix.com",
    "nameOldSport": ""
}