###
POST http://localhost:5000/teams/create
Content-Type: application/json

{
    "category": "P3",
    "email_club": "jeahdfushkfsfb@matrix.com"
}

###
GET http://localhost:5000/teams?id=e9e97e28-07b2-4f23-a5e4-49c23a08e2d1

###
PUT http://localhost:5000/teams/add
Content-Type: application/json

{
    "player":"dogbdfdfbbbb@front.com",
    "team":"e9e97e28-07b2-4f23-a5e4-49c23a08e2d1"
}


###
DELETE http://localhost:5000/teams/remove
Content-Type: application/json

{
    "player":"dogbdfdfbbb@front.com",
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}

###
PUT http://localhost:5000/teams/setCoach
Content-Type: application/json

{
    "coach":"jeanhuguhrsg@matrix.com",
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}


###
GET http://localhost:5000/teams/getCoach
Content-Type: application/json

{
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}

###
PUT http://localhost:5000/teams/updateCategory
Content-Type: application/json

{
    "team":"9cf78f80-59b2-41ce-b150-90c707861b08",
    "category":"P2 regionale"
}

### 
GET http://localhost:5000/teams/teamsPlayer?id_team=9cf78f80-59b2-41ce-b150-90c707861b08