###
POST http://localhost:5000/teams/create
Content-Type: application/json

{
    "category": "Soccer"
}

###
GET http://localhost:5000/teams?id=e9a59261-220e-4085-9bb9-a42e95a7e354

###
PUT http://localhost:5000/teams/add
Content-Type: application/json

{
    "player":"dogbdfdfbbb@front.com",
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}


###
DELETE http://localhost:5000/teams/remove
Content-Type: application/json

{
    "player":"dogbdfdfbbb@front.com",
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}

###
PUT http://localhost:5000/teams/setCoach
Content-Type: application/json

{
    "coach":"jeanhuguhrsg@matrix.com",
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}


###
GET http://localhost:5000/teams/getCoach
Content-Type: application/json

{
    "team":"e9a59261-220e-4085-9bb9-a42e95a7e354"
}