###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "lastname" : "MESSI",
    "firstname" : "GOAT",
    "email" : "dogbdfdfbbb@front.com",
    "password" : "yayayaya",
    "age" : 16,
    "role":"player"
}

### connection
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "dogb@front.com",
    "password" : "yayayaya"
}
###> {% client.global.set("token", response.body) %}


### verif token
POST http://localhost:5000/auth/confirm_token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzkyNGM5NWItZjNjYS00OWM5LWE1NGUtOTQ5ZWQ3MmUzNWQ1IiwiZXhwIjoxNjcwNzU4NTA1fQ.xn6jPw4HW6STttPy7JiNgeMYIw0jZ7XEyYPp2kcf3vE"
}

### wrong login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "dog@matrix.com",
    "password" : "yayay"
}

###
GET http://localhost:5000/users/id/rzeefz
###
GET http://localhost:5000/users/email/illls@matrix.com
GET http://localhost:5000/users


###
GET http://localhost:5000/users/myprofil
Content-Type: application/json
Authorize : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTA4NDRkZTMtMmEyOS00M2Q1LWI3MWYtYzIyYTU4OWQ1ZjFmIiwiZXhwIjoxNjcxMDIxMzg3fQ.Y5dHuQ0L2jb2goijVsqBkUc4J7O4ZOCgAoqbLj7o5gE


###
PUT http://localhost:5000/users/update
Content-Type: application/json
Authorize:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTA4NDRkZTMtMmEyOS00M2Q1LWI3MWYtYzIyYTU4OWQ1ZjFmIiwiZXhwIjoxNjcwOTQ1NDI0fQ.9bAeMXB4E5vRlwp3hi6I9Vop0x2fIIbh_YaSgyyRH-U

{  
    "firstname": "MESSI",
    "lastname": "le GOAT",
    "email": "dogb@front.com",
    "age": 16,
    "size": 186.9,  
    "weight": 79.9,
    "post":"place du GOAT",
    "number_year_experience": 189,
    "description": "je suis le GOATTT",
    "picture": "https://i.insider.com/602ee9ced3ad27001837f2ac?width=1000&format=jpeg&auto=webp"
}

###
GET http://localhost:5000/users/adresses?email=jeabn@matrix.com

###
GET http://localhost:5000/sports/userSport?email=jerome1@gmail.com

###
POST http://localhost:5000/users/applyClub
Content-Type: application/json

{
    "email_user": "jeabn@matrix.com",
    "email_club" : "jeab@matrix.com"
}

###
GET http://localhost:5000/users/userClub?email_user=jeabn@matrix.com

###
DELETE http://localhost:5000/users/leaveClub
Content-Type: application/json

{
    "email_user": "jeabn@matrix.com",
    "email_club" : "jeab@matrix.com"
}

### 
GET http://localhost:5000/users/isMember?email_user=jeabn@matrix.com


###
GET http://localhost:5000/users/searchUser?role=player&name=mar&country=Listembour

###
GET http://localhost:5000/users

###
GET http://localhost:5000/auth/getRole?email_user=illls@matrix.com