###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "lastname" : "marti",
    "firstname" : "jean",
    "email" : "jebn@matrix.com",
    "password" : "yayaya",
    "age" : 16
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "jeabn@matrix.com",
    "password" : "yayaya"
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "jeab@matrix.com",
    "password" : "marti"
}

###
GET http://localhost:5000/users

###
PUT http://localhost:5000/users/update
Content-Type: application/json

{  
    "firstname": "jean",
    "lastname": "marti",
    "email": "jeabn@matrix.com",
    "age": 16,
    "size": 186.9,
    "weight": 79.9,
    "post":"reserve",
    "number_year_experience": 189,
    "description": "je suis null",
    "picture": "https://i.insider.com/602ee9ced3ad27001837f2ac?width=1000&format=jpeg&auto=webp"
}

###
GET http://localhost:5000/users/adresses?role=player&email=jeabn@matrix.com

###
GET http://localhost:5000/sports/userSport?role=player&email=jeabn@matrix.com